### ISSUE TITLE
Add advanced filtering for the getHistory endpoint

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader_backend#74]
When we add advanced filtering on the microservices we will need to adjust the DBS to pass on the parameters. 

Related issues:
https://github.com/oceanprotocol/dbs_filecoin/issues/50
https://github.com/oceanprotocol/dbs_arweave/issues/41
https://github.com/oceanprotocol/dbs-ui-lib/issues/34

**Comment by AnaLoznianu** [comment]
For now, this is a super low priority. Let's make it and then we'll see
