### ISSUE TITLE
Validate the simplification of the code

### ISSUE THREAD

**Issue by balessan** [oceanprotocol/uploader_backend#80]
As isolated testing was required, we initially introduced some scripts and methods to manage the signature and nonce computation, so that we would not need any front-end.

As the integration advances, we need to make sure that no useless code lines remains.

Let's check that this week.

@jamiehewitt15 : Let me know if the commands to launch the DBS changed.

**Comment by jamiehewitt15** [comment]
Hi @balessan, the start process is the same as before and the commands are in the readme. If you encounter any issues let me know  

> Initialize Submodules: git submodule init git submodule update
Build Docker Image: docker build -t ocean-dbs .
Configure Environment: Copy contents of .env.example into .env and adjust necessary values.
Run Docker Compose: docker compose up

**Comment by AnaLoznianu** [comment]
@jamiehewitt15 Can we close this? I think we passed that phase

**Comment by jamiehewitt15** [comment]
@balessan can you update this issue with the changes that are still needed?
