### ISSUE TITLE
Update readme to reflect the name change from DBS to Uploader

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader_backend#86]
- Update readme to reflect the name change from DBS to Uploader

**Comment by AnaLoznianu** [comment]
Isn't this already done?

**Comment by AnaLoznianu** [comment]
Isn't this already done?

**Comment by jamiehewitt15** [comment]
The readme still says "OCEAN Decentralized Backend Storage"

**Comment by EnzoVezzaro** [comment]
I'll take this  👍🏽

**Comment by jamiehewitt15** [comment]
Ok cool, thanks @EnzoVezzaro
