### ISSUE TITLE
IPFS microservice

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/uploader_backend#87]
We will limit the file size to 10mb (configurable) 
We will charge 1 ocean/3 months (configurable token)  - we will not touch this wallet 
The flow will remain the same

**Comment by jamiehewitt15** [comment]
@AnaLoznianu @alexcos20 Is there already a spec for this?

**Comment by AnaLoznianu** [comment]
We need to respect the same specifications defined for arweave and filecoin.

**Comment by jamiehewitt15** [comment]
So we'll pin the file on our own IPFS cluster. The main remaining questions are about payment:

- Do we charge people?
- How much will we charge?
- What tokens do we accept payment in?

If we decide not to charge people we will most likely implement the following:
- 5mb maximum file upload
- New user flow that doesn't involve the user signing any transactions

**Comment by mihaisc** [comment]
@jamiehewitt15 updated the main description
